Random Forest:
              criterion: ['squared_error', 'friedman_mse', 'absolute_error', 'poisson']
              max_features: ['sqrt','log2',None]
              n_estimators': [8,16,32,64,128,256]
              n_jobs: [-1]
                
Decision Tree: 
              criterion: ['squared_error', 'friedman_mse', 'absolute_error', 'poisson']
              splitter: ['best','random']
              max_features: ['sqrt','log2']
               
Gradient Boosting:
              loss: ['squared_error', 'huber', 'absolute_error']
              subsample: [0.6,0.7,0.75]
              criterion: ['squared_error', 'friedman_mse']
              max_features: ['sqrt','log2']
              n_estimators: [8,16,64,128]
                
Linear Regression:

KNN Regressor:

XGB Regressor:
              learning_rate: [.1,.01,.05,.001]
              n_estimators: [8,16,32,64,128,256]
                
CatBoosting Regressor:
              depth: [6,8,10]
              learning_rate: [0.01, 0.05, 0.1]
              iterations: [30, 50, 100]
                
AdaBoost Regressor:
              learning_rate: [.1,.01,0.5,.001]
              loss: ['linear','square','exponential']
              n_estimators: [8,16,32,64,128,256]
                